---

- name: Set entry variables
  set_fact:
        baseuri:    '{{s_item.ilo_ip}}'
        username:   '{{s_item.ilo_username}}'
        password:   '{{s_item.ilo_password}}'

        datatype:   SystemAll

# -------------------- iLO queries start here

- name: Create session on {{ baseuri }}
  community.general.redfish_command:
        category:   Sessions
        command:    CreateSession
        baseuri:    "{{ baseuri }}"
        username:   "{{ username }}"
        password:   "{{ password }}"
  register: result

# --- Get iLO network inventory
- name: Get Manager NIC inventory
  redfish_info:
    category: Manager
    command: GetManagerNicInventory
    baseuri: "{{ baseuri }}"
    auth_token: "{{ result.session.token }}"
  register: result_nic

- name: Set endpoint
  set_fact:
      endpoint_ilo: "{{ result_nic.redfish_facts }}"

- name: Set iLO host name
  set_fact:
    ilohostname:              "{{endpoint_ilo.manager_nics.entries.0.1.0.FQDN}}" 
    odata_id:                 "{{endpoint_ilo.manager_nics.entries.0.0.resource_uri}}EthernetIntefaces/1/" 

 
    

# ---------------- Sub-inventories start here to collect information

- name: Initialize nic dataset
  set_fact:
    manager_nic_dataset:  []
    manager_ipv4_list:    []
    manager_ipv6_list:    []
    nic_dataset:          []
    ipv4_dataset:         []
    ipv6_dataset:         []
    ipv4_list:            []
    ipv6_list:            []



# --- Get iLO network information
- name: iLO network information {{ baseuri }}   
  include_tasks: nic-manager-sub-inventory.yml
  loop: "{{ endpoint_ilo.manager_nics.entries.0.1 }}" 
  when: item.Name == 'Manager Dedicated Network Interface'




# ---- Data Nics
# --- Get network information 
- name: Get Network Inventory on {{ baseuri }}
  ilo_network_info:
        category:   Network
        command:    GetNetworkInventory
        baseuri:    "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
  register: result_nic

- name: Set count
  set_fact:
      nic_count:    "{{  result_nic.redfish_facts.network.count }}"

- name: Set endpoint
  set_fact:
      nic_entries: "{{ result_nic.redfish_facts.network.entries }}"


- name: Data Nic information on {{ baseuri }}   
  include_tasks: nic-sub-inventory.yml
  loop: "{{ nic_entries }}"
  when: nic_count | int > 0




- name: Delete session on {{ baseuri }}
  community.general.redfish_command:
        category:     Sessions
        command:      DeleteSession
        baseuri:      "{{ baseuri }}"
        auth_token:   "{{ result.session.token }}"
        session_uri:  "{{ result.session.uri }}"
