---

- name: Set entry variables
  set_fact:
        baseuri:    '{{s_item.ilo_ip}}'
        username:   '{{s_item.ilo_username}}'
        password:   '{{s_item.ilo_password}}'

        datatype:   SystemAll

# -------------------- iLO queries start here

- name: Create session on {{ baseuri }}
  community.general.redfish_command:
        category:   Sessions
        command:    CreateSession
        baseuri:    "{{ baseuri }}"
        username:   "{{ username }}"
        password:   "{{ password }}"
  register: result

# --- Get systems inventory
- name: Get System Inventory on {{ baseuri }}
  community.general.redfish_info:
        category:   Systems
        command:    all
        baseuri:    "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
  register: result_inv

- name: Set endpoint
  set_fact:
        endpoint: "{{ result_inv.redfish_facts }}"

# --- Get Firmware inventory
- name: Get Firmware Inventory
  community.general.redfish_info:
    category:       Update
    command:        GetFirmwareInventory
    baseuri:        "{{ baseuri }}"
    auth_token:     "{{ result.session.token }}"
  register: result_fw

- name: Set endpoint
  set_fact:
        endpoint_fw: "{{ result_fw.redfish_facts }}"


# --- Get iLO network inventory
- name: Get Manager NIC inventory
  redfish_info:
    category: Manager
    command: GetManagerNicInventory
    baseuri: "{{ baseuri }}"
    auth_token: "{{ result.session.token }}"
  register: result_nic

- name: Set endpoint
  set_fact:
      endpoint_ilo: "{{ result_nic.redfish_facts }}"

- name: Set iLO host name
  set_fact:
    ilohostname:              "{{endpoint_ilo.manager_nics.entries.0.1.0.FQDN}}" 
    

# ---------------- Sub-inventories start here to collect information

# --- Get cpu information
- name: Get resource uri
  set_fact:
    resource:  "{{ endpoint.cpu.entries.0.0 | replace('resource_uri', 'system_uri')}}"


- name: CPU information on {{ baseuri }}   
  include_tasks: system-sub-inventory-cpu.yml
  loop: "{{ endpoint.cpu.entries.0.1 }}"
 

# ---- Get components firmware
- name: Set ilo_firmware variable   # Variable is updated in the sub-inventory-firmware playbook and used in sub-inventory-system
  set_fact:
      ilo_firmware: ""

- name: Get components firmware
  include_tasks: system-sub-inventory-firmware.yml
  loop: "{{ endpoint_fw.firmware.entries }}"


- name: Initialize compute dataset
  set_fact:
    compute_dataset:    []

- name: Get system inventory
  include_tasks: system-sub-inventory.yml


- name: Delete session on {{ baseuri }}
  community.general.redfish_command:
        category:     Sessions
        command:      DeleteSession
        baseuri:      "{{ baseuri }}"
        auth_token:   "{{ result.session.token }}"
        session_uri:  "{{ result.session.uri }}"
