
- name: Set Manager NIC - IP v4
  community.general.redfish_config:
    baseuri:    "{{ baseuri }}"
    auth_token: "{{ result.session.token }}"
    category: Manager
    command: SetManagerNic
    nic_config:
      DHCPv4:
        DHCPEnabled: False
      IPv4StaticAddresses:
        Address:  "{{ new_ilo_ip_v4 }}"
        Gateway: 10.100.1.254
        SubnetMask: 255.255.255.0